language: java
install: true

jdk:
  - oraclejdk8
  
before_cache:
  - rm -f  ~/.gradle/caches/modules-2/modules-2.lock
  - rm -fr ~/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - ~/.gradle/caches/
    - ~/.gradle/wrapper/

script:
  - ./gradlew build
  - ./gradlew test
