spring:
  profiles:
    active: ${PROFILE}
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT}
  servlet:
    multipart:
      ## MULTIPART (MultipartProperties)
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 2MB
      # Max Request Size
      max-request-size: 3MB
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENTID}
            clientSecret: ${GOOGLE_CLIENTSECRET}
            redirect-uri: ${GOOGLE_REDIRECT}
image:
  upload-dir: .assets/images
