spring:
  profiles:
    active: ${PROFILE}
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT}
  servlet:
    multipart:
      ## MULTIPART (MultipartProperties)
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 2MB
      # Max Request Size
      max-request-size: 3MB
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 22573920447-06l4jrtm9u1poo486qfdqi1n7cbj5mht.apps.googleusercontent.com
            clientSecret: 6E1iTJo_X303wlqXMYGCPe1c
            redirect-uri: http://localhost:8080/oauth2/callback/google
image:
  upload-dir: .assets/images
